######################################################################
# Automatically generated by qmake (3.0) Thu Oct 1 10:11:15 2015
######################################################################

TEMPLATE = app
TARGET = bowling
CONFIG -= qt
CONFIG += c++14
CONFIG += console
QT -= gui core

INCLUDEPATH = /usr/include/
LIBS += -pthread -lgtest -lgtest_main

# Input
SOURCES += main.cpp

HEADERS += bowling.hpp
